### ISSUE TITLE
on managed hosting, pdfs return blank even though file_get_contents, curl, and permissions are ok

### ISSUE THREAD

**Issue by airplanenoise** [anttiviljami/wp-pdf-templates#36]
@anttiviljami hi - i know this is not your main gig and that you don't use this much these days. 

i have spent tons of time trying to solve this issue. 

i read all the forums posts on WP, and a lot of stackoverflows about this. 

i have this working just fine on a VPS, on several websites, with the same hosting company (MT), exact same code. 
**on MANAGED HOSTING, the PDF returns blank**. the error logs show nothing I can solve:

[errors.zip](https://github.com/anttiviljami/wp-pdf-templates/files/7605549/errors.zip)
[errors.log](https://github.com/anttiviljami/wp-pdf-templates/files/7605551/errors.log)

i was told by the hosting's support that this can't work on this type of hosting, but i didn't believe it since file_get_content works, curl works, and i actually managed to generate a pdf with this test file: 

```
<?php

	$test = file_get_contents('https://DOMAIN_NAME_REMOVED/professionals/erica-wolff/pdf-preview', false);
	require_once 'wp-content/plugins/wp-pdf-templates/vendor/autoload.php';

    $dompdf = new Dompdf\Dompdf();

	define("DOMPDF_ENABLE_HTML5PARSER", true);

	$dompdf->loadHtml($test);
	
	// Render the HTML as PDF
	$dompdf->render();

	// Output the generated PDF to Browser
	// stream(filename [without .pdf], 1 compress, 1 force save dialog)
	$dompdf->stream('/var/www/wp-content/test123f.pdf',array('compress'=>0,'attachment'=>1));

?>
``` 

...going around all the Wordpress stuff found in the actual plugin. 

the result is very close the functioning one we have on our dev server, but only if i try to read from -template, from -preview it fails. 

[test123f.pdf (16).pdf](https://github.com/anttiviljami/wp-pdf-templates/files/7605561/test123f.pdf.16.pdf)

**what i am asking is this:** 
- obviously dompdf works on this environment
- i am able to generate a pdf with the layout that we want from the wordpress post 
- /pdf-template and /pdf-preview work fine 
- the pdf is blank, the stream part is blank, i attached it if someone speaks PDF :D 

if anybody has any insight on how to solve this, i would be grateful. i tried swapping dompdf versions, i tried outputting just the default template that comes with the plugin, i tried debugging verbosely... (by the way, how to get the same output as the debugger found on http://eclecticgeek.com/dompdf/debug.php ? the one that shows dependencies? i wasn't able to do that 

i am able to generate basic pdfs with just things like "hello world" — what fails is when i try to read content from an html. 

if anybody has had experience with that and solved it, i am willing to try your solution!

**my guess is that the managed hosting restrictions prevent from reading or writing the temp file**

i have to disable cache to make my test work, and the font cache folder never gets the .inc file or the font files. 

happy to jump on a discord if you want to check this out with me, i am totally stuck. 

thanks!

**Comment by anttiviljami** [comment]
Wow, have to admit I’m a bit surprised this code is still being used 😊

if I remember correctly I saw this issue when the /pdf-{preview,render} route was inaccessible from the host itself.

i think the plugin literally makes a http call to query the endpoint, so if the endpoint is behind auth or similar, it will fail. 

Might also want to check that you can read and write files in /tmp.

Are you able to turn on error logging on the host so you see any possible issues?

**Comment by airplanenoise** [comment]
Thanks for the reply!

Yes error logging is on and attached in the first message if you feel like looking at it. 

Basically can’t hit local host. But the error messages are about the 2 first attempts (the code tries to hit the content 3 times and eventually pings the permalink directly. 

…
--
Kaz

**Comment by anttiviljami** [comment]
Hi @airplanenoise 

```
file_get_contents(https://localhost/professionals/allegra-noonan/?pdf-template): failed to open stream: Address not available
```

Address not available sounds like `localhost` is not resolving to `127.0.0.1`

I would experiment with changing this line to point to either to public address or `127.0.0.1` https://github.com/anttiviljami/wp-pdf-templates/blob/master/wp-pdf-templates.php#L211

**Comment by airplanenoise** [comment]
thanks for the reply!

nah, i am still troubleshooting and i get further.

`[27-Nov-2021 15:20:35 UTC] PHP Warning:  A non-numeric value encountered
in
/var/www/wp-content/plugins/wp-pdf-templates/vendor/dompdf/dompdf/src/Css/Style.php
on line 1330`

this is the error i get.

it's just a warning.

and then the PDF is blank.

any ideas?

k

**Comment by airplanenoise** [comment]
thanks for the reply!

nah, i am still troubleshooting and i get further. 

`[27-Nov-2021 15:20:35 UTC] PHP Warning:  A non-numeric value encountered in /var/www/wp-content/plugins/wp-pdf-templates/vendor/dompdf/dompdf/src/Css/Style.php on line 1330`

this is the error i get. 

it's just a warning. 

and then the PDF is blank. 
[Vincent-Cavaliere.pdf.pdf](https://github.com/anttiviljami/wp-pdf-templates/files/7611949/Vincent-Cavaliere.pdf.pdf)


any ideas?

**Comment by anttiviljami** [comment]
Sorry, beyond that it's hard to say.

To troubleshoot, maybe add some logging and check if you're getting the right html at:

https://github.com/anttiviljami/wp-pdf-templates/blob/master/wp-pdf-templates.php#L260

**Comment by airplanenoise** [comment]
yeah... i do. i have one last question man, if you can: how do I specify a
tmp folder for the PDF to be generated? i think the last thing I need to
check before switching hosting... there seems to be a slew of options in
dompdf.

**Comment by airplanenoise** [comment]
ok - i was able to troubleshoot further. this is the error i get now: 

```
Stack trace:
#0 /var/www/wp-content/plugins/mfo-wp-pdf-templates/vendor/dompdf/dompdf/src/Dompdf.php(760): Dompdf\Dompdf->processHtml()
#1 /var/www/wp-content/plugins/mfo-wp-pdf-templates/wp-pdf-templates.php(404): Dompdf\Dompdf->render()
#2 /var/www/wp-content/plugins/mfo-wp-pdf-templates/wp-pdf-templates.php(263): _print_pdf('<html>\n<head>\n\t...')
#3 /var/www/wp-includes/class-wp-hook.php(303): _use_pdf_template('')
#4 /var/www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /var/www/wp-includes/template-loader.php(13): do_action('template_redire...')
#7 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...')
#8 /var/www/index.php(17): require('/var/www/wp-blo...')
#9 {main}
  thrown in /var/www/wp-content/plugins/mfo-wp-pdf-templates/vendor/dompdf/dompdf/src/Dompdf.php on line 596

```

does that make sense to you?

**Comment by anttiviljami** [comment]
That's just the stack trace. But yea
